version: '2'
services:

    # The environment variables default values determined on stage of
    # container start within starting script.
    btcd:
      image: btcd
      build:
        context: btcd/
      volumes:
        - shared:/rpc
        - bitcoin:/data
      container_name: btcd
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - DEBUG
        - MINING_ADDRESS
      entrypoint: ["./start-btcd.sh"]

    btcctl: 
      image: btcd
      build:
        context: btcd/
      container_name: btcctl
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
      volumes:
        - shared:/rpc
        - bitcoin:/data
      links:
        - "btcd:rpcserver"
      entrypoint: ["./start-btcctl.sh"]

    lnd-btc:
        image: lnd
        build:
          context: lnd/
        container_name: lnd-btc
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
          - shared:/rpc
        links:
          - "btcd:blockchain"
        entrypoint: ["./start-lnd.sh"]

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local   
